import React, { useState, useMemo, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sparkles } from "lucide-react";
import { apiCall, API_ENDPOINTS } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";

interface AutoGeneratedShowtime {
  id: number | null;
  date: string;
  hall_id: number;
  hall_name: string;
  movie_id: number;
  movie_title: string;
  start_time: string;
  end_time: string;
  priority: boolean;
}

interface AutoGenerateResponse {
  success: boolean;
  data: {
    summary: {
      dry_run: boolean;
      created_count: number;
      skipped_count: number;
    };
    created_showtimes: AutoGeneratedShowtime[];
  };
}

export function ManagerAutoGenerateDialog({ 
  cinemaId, 
  cinemaName, 
  moviesList, 
  onSuccess 
}: { 
  cinemaId: string;
  cinemaName: string;
  moviesList: { id: number; title: string; duration: number; age_rating: string; }[];
  onSuccess: () => void;
}) {
  const { toast } = useToast();
  const [isOpen, setIsOpen] = useState(false);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [rerollToken, setRerollToken] = useState<number>(0);
  const [autoPreview, setAutoPreview] = useState<AutoGeneratedShowtime[]>([]);
  const [hasPreview, setHasPreview] = useState(false);

  // Preview filters — same as Admin
  const [previewQuery, setPreviewQuery] = useState("");
  const [previewPage, setPreviewPage] = useState(1);
  const [previewMode, setPreviewMode] = useState<"list" | "by-day">("list");
  const [previewDateFilter, setPreviewDateFilter] = useState("all");
  const [previewHallFilter, setPreviewHallFilter] = useState("all");
  const [previewMovieFilter, setPreviewMovieFilter] = useState("all");
  const [previewOnlyPriority, setPreviewOnlyPriority] = useState(false);
  const [previewStartTimeFilter, setPreviewStartTimeFilter] = useState("");
  const [previewEndTimeFilter, setPreviewEndTimeFilter] = useState("");
  const previewPerPage = 25;

  const getTodayLocalDate = () => {
    const now = new Date();
    const tzOffsetMs = now.getTimezoneOffset() * 60 * 1000;
    return new Date(now.getTime() - tzOffsetMs).toISOString().split("T")[0];
  };

  const [autoForm, setAutoForm] = useState({
    startDate: getTodayLocalDate(),
    endDate: "",
    dayStartTime: "09:00",
    dayEndTime: "23:00",
    basePrice: "90000",
    priorityMovieIds: [] as string[],
    excludedMovieIds: [] as string[],
    priorityWeight: "3",
    maxShowtimesPerHallPerDay: "0",
  });

  // Reset preview when form changes
  useEffect(() => {
    setHasPreview(false);
    setAutoPreview([]);
  }, [autoForm]);

  // Reset page when filters change
  useEffect(() => {
    setPreviewPage(1);
  }, [previewQuery, autoPreview, previewDateFilter, previewHallFilter, previewMovieFilter, previewOnlyPriority, previewStartTimeFilter, previewEndTimeFilter]);

  const getErrorMessage = (error: unknown, fallback: string) => {
    if (error instanceof Error) return error.message;
    return fallback;
  };

  const handleAutoDialogOpenChange = (open: boolean) => {
    setIsOpen(open);
    if (!open) {
      setAutoPreview([]);
      setHasPreview(false);
      setRerollToken(0);
      setPreviewQuery("");
      setPreviewPage(1);
      setPreviewMode("list");
      setPreviewDateFilter("all");
      setPreviewHallFilter("all");
      setPreviewMovieFilter("all");
      setPreviewOnlyPriority(false);
      setPreviewStartTimeFilter("");
      setPreviewEndTimeFilter("");
      setAutoForm({
        startDate: getTodayLocalDate(),
        endDate: "",
        dayStartTime: "09:00",
        dayEndTime: "23:00",
        basePrice: "90000",
        priorityMovieIds: [],
        excludedMovieIds: [],
        priorityWeight: "3",
        maxShowtimesPerHallPerDay: "0",
      });
    } else {
      setAutoForm((prev) => ({
        ...prev,
        startDate: getTodayLocalDate(),
      }));
    }
  };

  const togglePriorityMovie = (movieId: string) => {
    setAutoForm((prev) => {
      const exists = prev.priorityMovieIds.includes(movieId);
      return {
        ...prev,
        priorityMovieIds: exists
          ? prev.priorityMovieIds.filter((id) => id !== movieId)
          : [...prev.priorityMovieIds, movieId],
        excludedMovieIds: prev.excludedMovieIds.filter((id) => id !== movieId),
      };
    });
  };

  const toggleExcludedMovie = (movieId: string) => {
    setAutoForm((prev) => {
      const exists = prev.excludedMovieIds.includes(movieId);
      return {
        ...prev,
        excludedMovieIds: exists
          ? prev.excludedMovieIds.filter((id) => id !== movieId)
          : [...prev.excludedMovieIds, movieId],
        priorityMovieIds: prev.priorityMovieIds.filter((id) => id !== movieId),
      };
    });
  };

  // ── Preview computed data (same logic as Admin) ──────────────────

  const previewMovieStats = useMemo(() => {
    const map = new Map<string, { movieTitle: string; total: number; priority: boolean }>();
    for (const item of autoPreview) {
      const existing = map.get(item.movie_title);
      if (existing) {
        existing.total += 1;
      } else {
        map.set(item.movie_title, { movieTitle: item.movie_title, total: 1, priority: item.priority });
      }
    }
    // Always show priority movies even if 0 showtimes
    for (const movieId of autoForm.priorityMovieIds) {
      const movie = moviesList.find((m) => String(m.id) === movieId);
      if (!movie) continue;
      if (!map.has(movie.title)) {
        map.set(movie.title, { movieTitle: movie.title, total: 0, priority: true });
      }
    }
    return Array.from(map.values()).sort((a, b) => b.total - a.total);
  }, [autoPreview, autoForm.priorityMovieIds, moviesList]);

  const previewDateOptions = useMemo(() => {
    return Array.from(new Set(autoPreview.map((item) => item.date))).sort();
  }, [autoPreview]);

  const previewHallOptions = useMemo(() => {
    const map = new Map<number, string>();
    for (const item of autoPreview) {
      map.set(item.hall_id, item.hall_name);
    }
    return Array.from(map.entries())
      .map(([id, name]) => ({ id: String(id), name }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [autoPreview]);

  const previewMovieOptions = useMemo(() => {
    const map = new Map<number, string>();
    for (const item of autoPreview) {
      map.set(item.movie_id, item.movie_title);
    }
    return Array.from(map.entries())
      .map(([id, title]) => ({ id: String(id), title }))
      .sort((a, b) => a.title.localeCompare(b.title));
  }, [autoPreview]);

  const filteredPreview = useMemo(() => {
    const q = previewQuery.trim().toLowerCase();
    return autoPreview.filter((item) => {
      const startsAt = new Date(item.start_time);
      const timeHHMM = startsAt.toTimeString().slice(0, 5);
      if (previewDateFilter !== "all" && item.date !== previewDateFilter) return false;
      if (previewHallFilter !== "all" && String(item.hall_id) !== previewHallFilter) return false;
      if (previewMovieFilter !== "all" && String(item.movie_id) !== previewMovieFilter) return false;
      if (previewOnlyPriority && !item.priority) return false;
      if (previewStartTimeFilter && timeHHMM < previewStartTimeFilter) return false;
      if (previewEndTimeFilter && timeHHMM > previewEndTimeFilter) return false;
      if (!q) return true;
      return (
        item.movie_title.toLowerCase().includes(q) ||
        item.hall_name.toLowerCase().includes(q) ||
        startsAt.toLocaleString("vi-VN").toLowerCase().includes(q)
      );
    });
  }, [autoPreview, previewQuery, previewDateFilter, previewHallFilter, previewMovieFilter, previewOnlyPriority, previewStartTimeFilter, previewEndTimeFilter]);

  const previewGroupedByDay = useMemo(() => {
    const groups = new Map<string, AutoGeneratedShowtime[]>();
    for (const item of filteredPreview) {
      const list = groups.get(item.date) || [];
      list.push(item);
      groups.set(item.date, list);
    }
    return Array.from(groups.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, items]) => ({
        date,
        items: items.sort((x, y) => x.start_time.localeCompare(y.start_time)),
      }));
  }, [filteredPreview]);

  const previewTotalPages = Math.max(1, Math.ceil(filteredPreview.length / previewPerPage));
  const previewItems = filteredPreview.slice((previewPage - 1) * previewPerPage, previewPage * previewPerPage);

  // ── API calls ──────────────────────────────────────────────────

  const requestAutoPreview = async (token: number) => {
    if (!cinemaId || !autoForm.startDate || !autoForm.endDate) {
      toast({ title: "Thiếu thông tin", description: "Vui lòng chọn ngày bắt đầu và ngày kết thúc", variant: "destructive" });
      return;
    }
    try {
      setAutoGenerating(true);
      const response = await apiCall<AutoGenerateResponse>(
        API_ENDPOINTS.SHOWTIMES_AUTO_GENERATE,
        {
          method: "POST",
          body: JSON.stringify({
            cinema_id: Number(cinemaId),
            start_date: autoForm.startDate,
            end_date: autoForm.endDate,
            day_start_time: autoForm.dayStartTime,
            day_end_time: autoForm.dayEndTime,
            base_price: Number(autoForm.basePrice) || 90000,
            priority_movie_ids: autoForm.priorityMovieIds.map(Number),
            excluded_movie_ids: autoForm.excludedMovieIds.map(Number),
            priority_weight: Number(autoForm.priorityWeight) || 3,
            max_showtimes_per_hall_per_day: Number(autoForm.maxShowtimesPerHallPerDay) || 0,
            reroll_token: token,
            dry_run: true,
          }),
        },
      );
      setRerollToken(token);
      setAutoPreview(response.data?.created_showtimes || []);
      setHasPreview(true);
      toast({ title: "Đã tạo bản xem trước", description: `Đã tạo ${response.data?.summary?.created_count ?? 0} suất chiếu, bỏ qua ${response.data?.summary?.skipped_count ?? 0} suất` });
    } catch (error: unknown) {
      toast({ title: "Lỗi xem trước", description: getErrorMessage(error, "Không thể xem trước lịch tự động"), variant: "destructive" });
    } finally {
      setAutoGenerating(false);
    }
  };

  const handleAutoPreview = async () => requestAutoPreview(Date.now());
  const handleAutoReroll = async () => requestAutoPreview(Date.now() + Math.floor(Math.random() * 1000));

  const handleAutoGenerate = async () => {
    if (!cinemaId || !autoForm.startDate || !autoForm.endDate) return;
    try {
      setAutoGenerating(true);
      const response = await apiCall<AutoGenerateResponse>(
        API_ENDPOINTS.SHOWTIMES_AUTO_GENERATE,
        {
          method: "POST",
          body: JSON.stringify({
            cinema_id: Number(cinemaId),
            start_date: autoForm.startDate,
            end_date: autoForm.endDate,
            day_start_time: autoForm.dayStartTime,
            day_end_time: autoForm.dayEndTime,
            base_price: Number(autoForm.basePrice) || 90000,
            priority_movie_ids: autoForm.priorityMovieIds.map(Number),
            excluded_movie_ids: autoForm.excludedMovieIds.map(Number),
            priority_weight: Number(autoForm.priorityWeight) || 3,
            max_showtimes_per_hall_per_day: Number(autoForm.maxShowtimesPerHallPerDay) || 0,
            reroll_token: rerollToken,
            dry_run: false,
          }),
        },
      );
      toast({ title: "Tạo lịch tự động thành công", description: `Đã tạo ${response.data?.summary?.created_count ?? 0} suất chiếu, bỏ qua ${response.data?.summary?.skipped_count ?? 0} suất` });
      setIsOpen(false);
      setAutoPreview([]);
      setHasPreview(false);
      onSuccess();
    } catch (error: unknown) {
      toast({ title: "Lỗi tạo lịch tự động", description: getErrorMessage(error, "Không thể tạo suất chiếu tự động"), variant: "destructive" });
    } finally {
      setAutoGenerating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleAutoDialogOpenChange}>
      <DialogTrigger asChild>
        <button className="flex items-center gap-2 h-10 px-4 rounded-xl font-medium text-sm transition-all border border-gray-200 text-gray-800 hover:bg-gray-50">
          <Sparkles className="w-4 h-4" />
          Tạo Tự Động
        </button>
      </DialogTrigger>
      <DialogContent className="w-[95vw] max-w-6xl max-h-[92vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Tạo Suất Chiếu Tự Động</DialogTitle>
          <DialogDescription>Hệ thống sẽ tự xếp lịch theo khung giờ và ưu tiên phim bạn chọn.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-2">
          {/* Cinema (locked) */}
          <div className="space-y-2">
            <Label>Rạp</Label>
            <Input disabled value={cinemaName || "Đang tải..."} />
          </div>

          {/* Date range */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Ngày bắt đầu</Label>
              <Input type="date" value={autoForm.startDate} onChange={(e) => setAutoForm((prev) => ({ ...prev, startDate: e.target.value }))} />
            </div>
            <div className="space-y-2">
              <Label>Ngày kết thúc</Label>
              <Input type="date" value={autoForm.endDate} onChange={(e) => setAutoForm((prev) => ({ ...prev, endDate: e.target.value }))} />
            </div>
          </div>

          {/* Time range */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Giờ bắt đầu trong ngày</Label>
              <Input type="time" value={autoForm.dayStartTime} onChange={(e) => setAutoForm((prev) => ({ ...prev, dayStartTime: e.target.value }))} />
            </div>
            <div className="space-y-2">
              <Label>Giờ kết thúc trong ngày</Label>
              <Input type="time" value={autoForm.dayEndTime} onChange={(e) => setAutoForm((prev) => ({ ...prev, dayEndTime: e.target.value }))} />
            </div>
          </div>

          {/* Price / weight / max */}
          <div className="grid grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label>Giá vé mặc định</Label>
              <Input type="number" value={autoForm.basePrice} onChange={(e) => setAutoForm((prev) => ({ ...prev, basePrice: e.target.value }))} />
            </div>
            <div className="space-y-2">
              <Label>Trọng số ưu tiên</Label>
              <Input type="number" min={1} value={autoForm.priorityWeight} onChange={(e) => setAutoForm((prev) => ({ ...prev, priorityWeight: e.target.value }))} />
            </div>
            <div className="space-y-2">
              <Label>Max suất/phòng/ngày (0 = không giới hạn)</Label>
              <Input type="number" min={0} value={autoForm.maxShowtimesPerHallPerDay} onChange={(e) => setAutoForm((prev) => ({ ...prev, maxShowtimesPerHallPerDay: e.target.value }))} />
            </div>
          </div>

          {/* Priority movies */}
          <div className="space-y-2">
            <Label>Chọn phim ưu tiên (chiếu nhiều hơn)</Label>
            <div className="max-h-44 overflow-auto rounded-md border p-3 grid grid-cols-2 gap-2">
              {moviesList.map((movie) => {
                const checked = autoForm.priorityMovieIds.includes(String(movie.id));
                const excluded = autoForm.excludedMovieIds.includes(String(movie.id));
                return (
                  <label key={movie.id} className={`flex items-center gap-2 text-sm ${excluded ? "opacity-40" : "cursor-pointer"}`}>
                    <input type="checkbox" checked={checked} disabled={excluded} onChange={() => togglePriorityMovie(String(movie.id))} />
                    <span className="truncate">{movie.title}</span>
                  </label>
                );
              })}
            </div>
          </div>

          {/* Excluded movies */}
          <div className="space-y-2">
            <Label>Chọn phim không xếp suất chiếu</Label>
            <div className="max-h-36 overflow-auto rounded-md border p-3 grid grid-cols-2 gap-2">
              {moviesList.map((movie) => {
                const excluded = autoForm.excludedMovieIds.includes(String(movie.id));
                const prioritized = autoForm.priorityMovieIds.includes(String(movie.id));
                return (
                  <label key={`excluded-${movie.id}`} className={`flex items-center gap-2 text-sm ${prioritized ? "opacity-40" : "cursor-pointer"}`}>
                    <input type="checkbox" checked={excluded} disabled={prioritized} onChange={() => toggleExcludedMovie(String(movie.id))} />
                    <span className="truncate">{movie.title}</span>
                  </label>
                );
              })}
            </div>
          </div>

          {/* ── Preview results (identical to Admin) ─────────────── */}
          {hasPreview && (
            <div className="space-y-2">
              <Label>Kết quả xem trước ({autoPreview.length} suất)</Label>
              
              {/* Movie stats summary */}
              <div className="rounded-md border p-3 bg-muted/30">
                <div className="text-sm font-medium mb-2">Tổng suất theo phim</div>
                <div className="grid grid-cols-2 gap-2">
                  {previewMovieStats.map((item) => (
                    <div key={item.movieTitle} className="text-sm rounded border bg-background px-2 py-1 flex items-center justify-between">
                      <span className="truncate pr-2">
                        {item.movieTitle}
                        {item.priority ? " (ưu tiên)" : ""}
                      </span>
                      <span className="font-semibold">{item.total}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Search + view mode */}
              <div className="space-y-2">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  <Input
                    placeholder="Tìm theo tên phim, phòng, thời gian..."
                    value={previewQuery}
                    onChange={(e) => setPreviewQuery(e.target.value)}
                  />
                  <Select value={previewMode} onValueChange={(value: "list" | "by-day") => setPreviewMode(value)}>
                    <SelectTrigger><SelectValue placeholder="Chế độ xem" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="list">Danh sách</SelectItem>
                      <SelectItem value="by-day">Xem theo ngày</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Filter row */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                  <Select value={previewDateFilter} onValueChange={setPreviewDateFilter}>
                    <SelectTrigger><SelectValue placeholder="Lọc ngày" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">Tất cả ngày</SelectItem>
                      {previewDateOptions.map((date) => (
                        <SelectItem key={date} value={date}>{new Date(date).toLocaleDateString("vi-VN")}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={previewMovieFilter} onValueChange={setPreviewMovieFilter}>
                    <SelectTrigger><SelectValue placeholder="Lọc phim" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">Tất cả phim</SelectItem>
                      {previewMovieOptions.map((movie) => (
                        <SelectItem key={movie.id} value={movie.id}>{movie.title}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Select value={previewHallFilter} onValueChange={setPreviewHallFilter}>
                    <SelectTrigger><SelectValue placeholder="Lọc phòng" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">Tất cả phòng</SelectItem>
                      {previewHallOptions.map((hall) => (
                        <SelectItem key={hall.id} value={hall.id}>{hall.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <label className="flex items-center gap-2 text-sm rounded-md border px-3">
                    <input type="checkbox" checked={previewOnlyPriority} onChange={(e) => setPreviewOnlyPriority(e.target.checked)} />
                    Chỉ phim ưu tiên
                  </label>
                </div>

                {/* Time range filter */}
                <div className="grid grid-cols-2 gap-2">
                  <Input type="time" value={previewStartTimeFilter} onChange={(e) => setPreviewStartTimeFilter(e.target.value)} placeholder="Từ giờ" />
                  <Input type="time" value={previewEndTimeFilter} onChange={(e) => setPreviewEndTimeFilter(e.target.value)} placeholder="Đến giờ" />
                </div>

                {/* Preview list / by-day */}
                <div className="max-h-72 overflow-auto rounded-md border p-2">
                  {previewMode === "by-day" ? (
                    previewGroupedByDay.length > 0 ? (
                      previewGroupedByDay.map((group) => (
                        <div key={group.date} className="mb-3 last:mb-0">
                          <div className="text-sm font-semibold sticky top-0 bg-background py-1">
                            {new Date(group.date).toLocaleDateString("vi-VN")} ({group.items.length} suất)
                          </div>
                          {group.items.map((item, idx) => (
                            <div key={`${group.date}-${item.start_time}-${item.movie_id}-${idx}`} className="text-sm py-1 border-b last:border-b-0">
                              {new Date(item.start_time).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}
                              {" - "}
                              {item.movie_title}
                              {item.priority ? " (ưu tiên)" : ""}
                              {" - "}
                              {item.hall_name}
                            </div>
                          ))}
                        </div>
                      ))
                    ) : (
                      <div className="text-sm text-muted-foreground py-2">Không có suất nào khớp bộ lọc.</div>
                    )
                  ) : previewItems.length > 0 ? (
                    previewItems.map((item, idx) => (
                      <div key={`${item.start_time}-${item.movie_id}-${idx}`} className="text-sm py-1 border-b last:border-b-0">
                        {new Date(item.start_time).toLocaleString("vi-VN")} - {item.movie_title}
                        {item.priority ? " (ưu tiên)" : ""}
                        {" - "}
                        {item.hall_name}
                      </div>
                    ))
                  ) : (
                    <div className="text-sm text-muted-foreground py-2">Không có suất nào khớp bộ lọc.</div>
                  )}
                </div>

                {/* Pagination (list mode only) */}
                {previewMode === "list" && (
                  <div className="flex items-center justify-between text-xs text-muted-foreground">
                    <span>
                      Hiển thị {filteredPreview.length === 0 ? 0 : (previewPage - 1) * previewPerPage + 1}
                      -{Math.min(previewPage * previewPerPage, filteredPreview.length)}
                      /{filteredPreview.length}
                    </span>
                    <div className="flex items-center gap-2">
                      <Button variant="outline" size="sm" disabled={previewPage <= 1} onClick={() => setPreviewPage((p) => Math.max(1, p - 1))}>
                        Trước
                      </Button>
                      <span>{previewPage}/{previewTotalPages}</span>
                      <Button variant="outline" size="sm" disabled={previewPage >= previewTotalPages} onClick={() => setPreviewPage((p) => Math.min(previewTotalPages, p + 1))}>
                        Sau
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Footer buttons */}
        <DialogFooter className="sticky bottom-0 bg-background pt-3">
          <Button variant="outline" onClick={() => handleAutoDialogOpenChange(false)}>
            Hủy
          </Button>
          <Button variant="outline" onClick={handleAutoPreview} disabled={autoGenerating}>
            {autoGenerating ? "Đang xử lý..." : "Xem trước"}
          </Button>
          <Button variant="outline" onClick={handleAutoReroll} disabled={autoGenerating || !hasPreview}>
            {autoGenerating ? "Đang xếp lại..." : "Xếp lại"}
          </Button>
          <Button onClick={handleAutoGenerate} disabled={autoGenerating || !hasPreview}>
            {autoGenerating ? "Đang tạo..." : "Tạo lịch từ bản xem trước"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
