import React, { useState, useEffect, useCallback, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import {
  Plus,
  Search,
  Edit,
  Trash2,
  Film,
  Calendar as CalendarIcon,
  Clock,
  AlertTriangle,
  Armchair,
  Sparkles,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";
import { useToast } from "@/hooks/use-toast";
import { API_ENDPOINTS, apiCall } from "@/lib/api";
import {
  detectScheduleConflict,
  checkVietnameseQuota,
  calculateShowtimeEnd,
} from "@/lib/validation";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface Showtime {
  id: string;
  movieId: string;
  movieTitle: string;
  cinemaId: string;
  cinemaName: string;
  hallId: string;
  room: string;
  date: string;
  time: string;
  price: number;
  availableSeats: number;
  totalSeats: number;
  status: "scheduled" | "ongoing" | "completed" | "cancelled";
  duration: number;
}

interface BackendMovie {
  id: number;
  title: string;
  duration_minutes: number;
  status: string;
  origin: string;
}

interface BackendCinema {
  id: number;
  name: string;
  address: string;
}

interface BackendHall {
  id: number;
  name: string;
  total_seats: number;
}

interface BackendShowtime {
  id: number;
  movie_title: string;
  movie_id: number;
  cinema_id: number;
  cinema_name: string;
  cinema_hall_id: number;
  hall_name: string;
  start_time: string;
  total_seats: number;
  sold_seats?: number;
  base_price?: number;
  duration_minutes: number;
}

interface AutoGeneratedShowtime {
  id: number | null;
  date: string;
  hall_id: number;
  hall_name: string;
  movie_id: number;
  movie_title: string;
  start_time: string;
  end_time: string;
  priority: boolean;
}

interface AutoGenerateResponse {
  success: boolean;
  data: {
    summary: {
      dry_run: boolean;
      created_count: number;
      skipped_count: number;
    };
    created_showtimes: AutoGeneratedShowtime[];
  };
}

const AdminScheduler: React.FC = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState("");
  const [filterDate, setFilterDate] = useState("all");
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isAutoDialogOpen, setIsAutoDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedShowtime, setSelectedShowtime] = useState<Showtime | null>(
    null,
  );
  const [searchCategory, setSearchCategory] = useState<
    "movie" | "cinema" | "room"
  >("movie");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 15;

  const [showtimes, setShowtimes] = useState<Showtime[]>([]);
  const [moviesList, setMoviesList] = useState<BackendMovie[]>([]);
  const [cinemasList, setCinemasList] = useState<BackendCinema[]>([]);
  const [hallsList, setHallsList] = useState<BackendHall[]>([]);
  const [loadingHalls, setLoadingHalls] = useState(false);
  const [loading, setLoading] = useState(true);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoPreview, setAutoPreview] = useState<AutoGeneratedShowtime[]>([]);
  const [hasPreview, setHasPreview] = useState(false);
  const [previewQuery, setPreviewQuery] = useState("");
  const [previewPage, setPreviewPage] = useState(1);
  const [previewMode, setPreviewMode] = useState<"list" | "by-day">("list");
  const [previewDateFilter, setPreviewDateFilter] = useState("all");
  const [previewHallFilter, setPreviewHallFilter] = useState("all");
  const [previewMovieFilter, setPreviewMovieFilter] = useState("all");
  const [previewOnlyPriority, setPreviewOnlyPriority] = useState(false);
  const [previewStartTimeFilter, setPreviewStartTimeFilter] = useState("");
  const [previewEndTimeFilter, setPreviewEndTimeFilter] = useState("");
  const [rerollToken, setRerollToken] = useState<number>(0);
  const previewPerPage = 25;

  const getTodayLocalDate = () => {
    const now = new Date();
    const tzOffsetMs = now.getTimezoneOffset() * 60 * 1000;
    return new Date(now.getTime() - tzOffsetMs).toISOString().split("T")[0];
  };

  const getErrorMessage = (error: unknown, fallback: string) => {
    if (error instanceof Error && error.message) return error.message;
    return fallback;
  };

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      const [moviesRes, cinemasRes, showtimesRes] = await Promise.all([
        apiCall<{
          success: boolean;
          data: { movies: BackendMovie[]; pagination: unknown };
        }>(`${API_ENDPOINTS.MOVIES}?limit=200`),
        apiCall<{ success: boolean; data: { cinemas: BackendCinema[] } }>(
          API_ENDPOINTS.CINEMAS,
        ),
        apiCall<{ success: boolean; data: { showtimes: BackendShowtime[] } }>(
          `${API_ENDPOINTS.SHOWTIMES}?limit=5000`,
        ),
      ]);

      setMoviesList(moviesRes.data?.movies || []);
      setCinemasList(cinemasRes.data?.cinemas || []);

      const backendShowtimes = showtimesRes.data?.showtimes || [];
      const mapped: Showtime[] = backendShowtimes.map((s) => {
        const startDate = new Date(s.start_time);
        const tzOffsetMs = startDate.getTimezoneOffset() * 60000;
        return {
          id: String(s.id),
          movieId: String(s.movie_id),
          movieTitle: s.movie_title,
          cinemaId: String(s.cinema_id),
          cinemaName: s.cinema_name,
          hallId: String(s.cinema_hall_id),
          room: s.hall_name,
          date: new Date(startDate.getTime() - tzOffsetMs)
            .toISOString()
            .split("T")[0],
          time: startDate.toLocaleTimeString("en-GB", {
            hour: "2-digit",
            minute: "2-digit",
          }),
          price: s.base_price || 90000,
          availableSeats: (s.total_seats || 0) - (s.sold_seats || 0),
          totalSeats: s.total_seats || 0,
          status: startDate > new Date() ? "scheduled" : "completed",
          duration: s.duration_minutes || 0,
        };
      });
      setShowtimes(mapped);
    } catch (error) {
      console.error("Failed to fetch scheduler data:", error);
      toast({
        title: "Lỗi",
        description: "Không thể tải dữ liệu lịch chiếu",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const [formData, setFormData] = useState({
    movieId: "",
    cinemaId: "",
    hallId: "",
    date: "",
    time: "",
    price: "",
  });

  const [autoForm, setAutoForm] = useState({
    cinemaId: "",
    startDate: getTodayLocalDate(),
    endDate: "",
    dayStartTime: "09:00",
    dayEndTime: "23:00",
    basePrice: "90000",
    priorityMovieIds: [] as string[],
    excludedMovieIds: [] as string[],
    priorityWeight: "3",
    maxShowtimesPerHallPerDay: "0",
  });

  useEffect(() => {
    setHasPreview(false);
    setAutoPreview([]);
  }, [autoForm]);

  const handleAutoDialogOpenChange = (open: boolean) => {
    setIsAutoDialogOpen(open);
    if (!open) return;

    setAutoForm((prev) => ({
      ...prev,
      startDate: getTodayLocalDate(),
    }));
  };

  useEffect(() => {
    setPreviewPage(1);
  }, [
    previewQuery,
    autoPreview,
    previewDateFilter,
    previewHallFilter,
    previewMovieFilter,
    previewOnlyPriority,
    previewStartTimeFilter,
    previewEndTimeFilter,
  ]);

  const previewMovieStats = useMemo(() => {
    const map = new Map<
      string,
      { movieTitle: string; total: number; priority: boolean }
    >();
    for (const item of autoPreview) {
      const existing = map.get(item.movie_title);
      if (existing) {
        existing.total += 1;
      } else {
        map.set(item.movie_title, {
          movieTitle: item.movie_title,
          total: 1,
          priority: item.priority,
        });
      }
    }

    // Luon hien thi phim uu tien da chon, ke ca khi chua co suat nao
    for (const movieId of autoForm.priorityMovieIds) {
      const movie = moviesList.find((m) => String(m.id) === movieId);
      if (!movie) continue;

      if (!map.has(movie.title)) {
        map.set(movie.title, {
          movieTitle: movie.title,
          total: 0,
          priority: true,
        });
      }
    }

    return Array.from(map.values()).sort((a, b) => b.total - a.total);
  }, [autoPreview, autoForm.priorityMovieIds, moviesList]);

  const previewDateOptions = useMemo(() => {
    return Array.from(new Set(autoPreview.map((item) => item.date))).sort();
  }, [autoPreview]);

  const previewHallOptions = useMemo(() => {
    const map = new Map<number, string>();
    for (const item of autoPreview) {
      map.set(item.hall_id, item.hall_name);
    }
    return Array.from(map.entries())
      .map(([id, name]) => ({ id: String(id), name }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [autoPreview]);

  const previewMovieOptions = useMemo(() => {
    const map = new Map<number, string>();
    for (const item of autoPreview) {
      map.set(item.movie_id, item.movie_title);
    }
    return Array.from(map.entries())
      .map(([id, title]) => ({ id: String(id), title }))
      .sort((a, b) => a.title.localeCompare(b.title));
  }, [autoPreview]);

  const filteredPreview = useMemo(() => {
    const q = previewQuery.trim().toLowerCase();
    return autoPreview.filter((item) => {
      const startsAt = new Date(item.start_time);
      const timeHHMM = startsAt.toTimeString().slice(0, 5);

      if (previewDateFilter !== "all" && item.date !== previewDateFilter)
        return false;
      if (
        previewHallFilter !== "all" &&
        String(item.hall_id) !== previewHallFilter
      )
        return false;
      if (
        previewMovieFilter !== "all" &&
        String(item.movie_id) !== previewMovieFilter
      )
        return false;
      if (previewOnlyPriority && !item.priority) return false;
      if (previewStartTimeFilter && timeHHMM < previewStartTimeFilter)
        return false;
      if (previewEndTimeFilter && timeHHMM > previewEndTimeFilter) return false;

      if (!q) return true;
      return (
        item.movie_title.toLowerCase().includes(q) ||
        item.hall_name.toLowerCase().includes(q) ||
        startsAt.toLocaleString("vi-VN").toLowerCase().includes(q)
      );
    });
  }, [
    autoPreview,
    previewQuery,
    previewDateFilter,
    previewHallFilter,
    previewMovieFilter,
    previewOnlyPriority,
    previewStartTimeFilter,
    previewEndTimeFilter,
  ]);

  const previewGroupedByDay = useMemo(() => {
    const groups = new Map<string, AutoGeneratedShowtime[]>();
    for (const item of filteredPreview) {
      const list = groups.get(item.date) || [];
      list.push(item);
      groups.set(item.date, list);
    }
    return Array.from(groups.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, items]) => ({
        date,
        items: items.sort((x, y) => x.start_time.localeCompare(y.start_time)),
      }));
  }, [filteredPreview]);

  const previewTotalPages = Math.max(
    1,
    Math.ceil(filteredPreview.length / previewPerPage),
  );

  const previewItems = filteredPreview.slice(
    (previewPage - 1) * previewPerPage,
    previewPage * previewPerPage,
  );

  // Load halls when cinema changes
  useEffect(() => {
    if (!formData.cinemaId) {
      setHallsList([]);
      setFormData((prev) => ({ ...prev, hallId: "" }));
      return;
    }
    const loadHalls = async () => {
      setLoadingHalls(true);
      try {
        const res = await apiCall<{
          success: boolean;
          data: { halls: BackendHall[] };
        }>(API_ENDPOINTS.CINEMA_HALLS(Number(formData.cinemaId)));
        setHallsList(res.data?.halls || []);
      } catch {
        setHallsList([]);
      } finally {
        setLoadingHalls(false);
      }
    };
    loadHalls();
  }, [formData.cinemaId]);

  // Clear errors when form data changes
  useEffect(() => {
    setConflictError(null);
    setQuotaWarning(null);
  }, [formData]);

  const [quotaWarning, setQuotaWarning] = useState<string | null>(null);
  const [conflictError, setConflictError] = useState<string | null>(null);

  const filteredShowtimes = showtimes
    .filter((showtime) => {
      const query = searchQuery.toLowerCase();
      switch (searchCategory) {
        case "cinema":
          if (!showtime.cinemaName.toLowerCase().includes(query)) return false;
          break;
        case "room":
          if (!showtime.room.toLowerCase().includes(query)) return false;
          break;
        default:
          if (!showtime.movieTitle.toLowerCase().includes(query)) return false;
      }
      if (dateFrom && showtime.date < dateFrom) return false;
      if (dateTo && showtime.date > dateTo) return false;
      return true;
    })
    .sort((a, b) => {
      const priority = {
        ongoing: 1,
        scheduled: 2,
        completed: 3,
        cancelled: 4,
      };
      return priority[a.status] - priority[b.status];
    });

  const totalPages = Math.ceil(filteredShowtimes.length / itemsPerPage);
  const paginatedShowtimes = filteredShowtimes.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage,
  );

  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, searchCategory, filterDate, dateFrom, dateTo]);

  const handleAdd = async () => {
    const movie = moviesList.find((m) => String(m.id) === formData.movieId);
    const cinema = cinemasList.find((c) => String(c.id) === formData.cinemaId);

    if (!movie || !cinema || !formData.hallId) return;

    setConflictError(null);

    try {
      const startTime = `${formData.date} ${formData.time}:00`;
      await apiCall(API_ENDPOINTS.SHOWTIMES, {
        method: "POST",
        body: JSON.stringify({
          movie_id: movie.id,
          cinema_hall_id: Number(formData.hallId),
          start_time: startTime,
          base_price: Number(formData.price) || 90000,
        }),
      });

      toast({
        title: "Thêm lịch chiếu thành công",
        description: `Đã thêm suất chiếu ${movie.title}`,
      });
      setIsAddDialogOpen(false);
      setFormData({
        movieId: "",
        cinemaId: "",
        hallId: "",
        date: "",
        time: "",
        price: "",
      });
      setHallsList([]);
      await fetchData();
    } catch (error: unknown) {
      const message = getErrorMessage(error, "Không thể thêm suất chiếu");
      if (message.includes("Trùng lịch") || message.includes("conflict")) {
        setConflictError(message);
      } else {
        toast({
          title: "Lỗi",
          description: message,
          variant: "destructive",
        });
      }
    }
  };

  const handleDelete = async (id: string, title: string) => {
    try {
      await apiCall(`${API_ENDPOINTS.SHOWTIMES}/${id}`, {
        method: "DELETE",
      });
      setShowtimes(showtimes.filter((s) => s.id !== id));
      toast({
        title: "Xóa lịch chiếu thành công",
        description: `Đã xóa suất chiếu ${title}`,
      });
    } catch (error) {
      toast({
        title: "Lỗi",
        description: "Không thể xóa suất chiếu",
        variant: "destructive",
      });
    }
  };

  const togglePriorityMovie = (movieId: string) => {
    setAutoForm((prev) => {
      const exists = prev.priorityMovieIds.includes(movieId);
      return {
        ...prev,
        priorityMovieIds: exists
          ? prev.priorityMovieIds.filter((id) => id !== movieId)
          : [...prev.priorityMovieIds, movieId],
        // Neu da uu tien phim thi bo phim do ra khoi danh sach loai tru
        excludedMovieIds: prev.excludedMovieIds.filter((id) => id !== movieId),
      };
    });
  };

  const toggleExcludedMovie = (movieId: string) => {
    setAutoForm((prev) => {
      const exists = prev.excludedMovieIds.includes(movieId);
      return {
        ...prev,
        excludedMovieIds: exists
          ? prev.excludedMovieIds.filter((id) => id !== movieId)
          : [...prev.excludedMovieIds, movieId],
        // Neu da loai tru phim thi bo phim do ra khoi uu tien de tranh xung dot
        priorityMovieIds: prev.priorityMovieIds.filter((id) => id !== movieId),
      };
    });
  };

  const handleAutoGenerate = async () => {
    if (!autoForm.cinemaId || !autoForm.startDate || !autoForm.endDate) {
      toast({
        title: "Thiếu thông tin",
        description: "Vui lòng chọn rạp, ngày bắt đầu và ngày kết thúc",
        variant: "destructive",
      });
      return;
    }

    try {
      setAutoGenerating(true);
      const response = await apiCall<AutoGenerateResponse>(
        API_ENDPOINTS.SHOWTIMES_AUTO_GENERATE,
        {
          method: "POST",
          body: JSON.stringify({
            cinema_id: Number(autoForm.cinemaId),
            start_date: autoForm.startDate,
            end_date: autoForm.endDate,
            day_start_time: autoForm.dayStartTime,
            day_end_time: autoForm.dayEndTime,
            base_price: Number(autoForm.basePrice) || 90000,
            priority_movie_ids: autoForm.priorityMovieIds.map(Number),
            excluded_movie_ids: autoForm.excludedMovieIds.map(Number),
            priority_weight: Number(autoForm.priorityWeight) || 3,
            max_showtimes_per_hall_per_day:
              Number(autoForm.maxShowtimesPerHallPerDay) || 0,
            reroll_token: rerollToken,
            dry_run: false,
          }),
        },
      );

      toast({
        title: "Tạo lịch tự động thành công",
        description: `Đã tạo ${response.data?.summary?.created_count ?? 0} suất chiếu, bỏ qua ${response.data?.summary?.skipped_count ?? 0} suất`,
      });

      setIsAutoDialogOpen(false);
      setAutoPreview([]);
      setHasPreview(false);
      await fetchData();
    } catch (error: unknown) {
      toast({
        title: "Lỗi tạo lịch tự động",
        description: getErrorMessage(error, "Không thể tạo suất chiếu tự động"),
        variant: "destructive",
      });
    } finally {
      setAutoGenerating(false);
    }
  };

  const requestAutoPreview = async (token: number) => {
    if (!autoForm.cinemaId || !autoForm.startDate || !autoForm.endDate) {
      toast({
        title: "Thiếu thông tin",
        description: "Vui lòng chọn rạp, ngày bắt đầu và ngày kết thúc",
        variant: "destructive",
      });
      return;
    }

    try {
      setAutoGenerating(true);
      const response = await apiCall<AutoGenerateResponse>(
        API_ENDPOINTS.SHOWTIMES_AUTO_GENERATE,
        {
          method: "POST",
          body: JSON.stringify({
            cinema_id: Number(autoForm.cinemaId),
            start_date: autoForm.startDate,
            end_date: autoForm.endDate,
            day_start_time: autoForm.dayStartTime,
            day_end_time: autoForm.dayEndTime,
            base_price: Number(autoForm.basePrice) || 90000,
            priority_movie_ids: autoForm.priorityMovieIds.map(Number),
            excluded_movie_ids: autoForm.excludedMovieIds.map(Number),
            priority_weight: Number(autoForm.priorityWeight) || 3,
            max_showtimes_per_hall_per_day:
              Number(autoForm.maxShowtimesPerHallPerDay) || 0,
            reroll_token: token,
            dry_run: true,
          }),
        },
      );

      setRerollToken(token);
      setAutoPreview(response.data?.created_showtimes || []);
      setHasPreview(true);

      toast({
        title: "Đã tạo bản xem trước",
        description: `Đã tạo ${response.data?.summary?.created_count ?? 0} suất chiếu, bỏ qua ${response.data?.summary?.skipped_count ?? 0} suất`,
      });
    } catch (error: unknown) {
      toast({
        title: "Lỗi xem trước",
        description: getErrorMessage(error, "Không thể xem trước lịch tự động"),
        variant: "destructive",
      });
    } finally {
      setAutoGenerating(false);
    }
  };

  const handleAutoPreview = async () => {
    await requestAutoPreview(Date.now());
  };

  const handleAutoReroll = async () => {
    await requestAutoPreview(Date.now() + Math.floor(Math.random() * 1000));
  };

  const handleEdit = (showtime: Showtime) => {
    setSelectedShowtime(showtime);
    setIsEditDialogOpen(true);
  };

  const handleUpdate = async () => {
    if (selectedShowtime) {
      try {
        const startTime = `${selectedShowtime.date} ${selectedShowtime.time}:00`;
        await apiCall(`${API_ENDPOINTS.SHOWTIMES}/${selectedShowtime.id}`, {
          method: "PUT",
          body: JSON.stringify({
            movie_id: Number(selectedShowtime.movieId),
            start_time: startTime,
            base_price: selectedShowtime.price,
          }),
        });
        toast({
          title: "Cập nhật lịch chiếu thành công",
          description: `Đã cập nhật suất chiếu ${selectedShowtime.movieTitle}`,
        });
        setIsEditDialogOpen(false);
        setSelectedShowtime(null);
        await fetchData();
      } catch (error: unknown) {
        const message = getErrorMessage(error, "Không thể cập nhật suất chiếu");
        toast({
          title: "Lỗi",
          description: message,
          variant: "destructive",
        });
      }
    }
  };

  const getStatusBadge = (status: string) => {
    const variants = {
      scheduled: "bg-blue-500",
      ongoing: "bg-green-500",
      completed: "bg-gray-500",
      cancelled: "bg-red-500",
    };
    const labels = {
      scheduled: "Đã xếp",
      ongoing: "Đang chiếu",
      completed: "Đã chiếu",
      cancelled: "Đã hủy",
    };
    return (
      <Badge
        className={`${variants[status as keyof typeof variants]} text-white`}
      >
        {labels[status as keyof typeof labels]}
      </Badge>
    );
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString("vi-VN");
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Quản Lý Lịch Chiếu</h1>
          <p className="text-muted-foreground">
            Xếp lịch và quản lý suất chiếu phim
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Dialog
            open={isAutoDialogOpen}
            onOpenChange={handleAutoDialogOpenChange}
          >
            <DialogTrigger asChild>
              <Button variant="outline" className="gap-2">
                <Sparkles className="w-4 h-4" />
                Tạo Tự Động
              </Button>
            </DialogTrigger>
            <DialogContent className="w-[95vw] max-w-6xl max-h-[92vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Tạo Suất Chiếu Tự Động</DialogTitle>
                <DialogDescription>
                  Hệ thống sẽ tự xếp lịch theo khung giờ và ưu tiên phim bạn
                  chọn.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-2">
                <div className="space-y-2">
                  <Label>Rạp</Label>
                  <Select
                    value={autoForm.cinemaId}
                    onValueChange={(value) =>
                      setAutoForm((prev) => ({ ...prev, cinemaId: value }))
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Chọn rạp" />
                    </SelectTrigger>
                    <SelectContent>
                      {cinemasList.map((cinema) => (
                        <SelectItem key={cinema.id} value={String(cinema.id)}>
                          {cinema.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Ngày bắt đầu</Label>
                    <Input
                      type="date"
                      value={autoForm.startDate}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          startDate: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Ngày kết thúc</Label>
                    <Input
                      type="date"
                      value={autoForm.endDate}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          endDate: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Giờ bắt đầu trong ngày</Label>
                    <Input
                      type="time"
                      value={autoForm.dayStartTime}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          dayStartTime: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Giờ kết thúc trong ngày</Label>
                    <Input
                      type="time"
                      value={autoForm.dayEndTime}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          dayEndTime: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <Label>Giá vé mặc định</Label>
                    <Input
                      type="number"
                      value={autoForm.basePrice}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          basePrice: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Trọng số ưu tiên</Label>
                    <Input
                      type="number"
                      min={1}
                      value={autoForm.priorityWeight}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          priorityWeight: e.target.value,
                        }))
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Max suất/phòng/ngày (0 = không giới hạn)</Label>
                    <Input
                      type="number"
                      min={0}
                      value={autoForm.maxShowtimesPerHallPerDay}
                      onChange={(e) =>
                        setAutoForm((prev) => ({
                          ...prev,
                          maxShowtimesPerHallPerDay: e.target.value,
                        }))
                      }
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Chọn phim ưu tiên (chiếu nhiều hơn)</Label>
                  <div className="max-h-44 overflow-auto rounded-md border p-3 grid grid-cols-2 gap-2">
                    {moviesList.map((movie) => {
                      const checked = autoForm.priorityMovieIds.includes(
                        String(movie.id),
                      );
                      const excluded = autoForm.excludedMovieIds.includes(
                        String(movie.id),
                      );
                      return (
                        <label
                          key={movie.id}
                          className={`flex items-center gap-2 text-sm ${excluded ? "opacity-40" : "cursor-pointer"}`}
                        >
                          <input
                            type="checkbox"
                            checked={checked}
                            disabled={excluded}
                            onChange={() =>
                              togglePriorityMovie(String(movie.id))
                            }
                          />
                          <span className="truncate">{movie.title}</span>
                        </label>
                      );
                    })}
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Chọn phim không xếp suất chiếu</Label>
                  <div className="max-h-36 overflow-auto rounded-md border p-3 grid grid-cols-2 gap-2">
                    {moviesList.map((movie) => {
                      const excluded = autoForm.excludedMovieIds.includes(
                        String(movie.id),
                      );
                      const prioritized = autoForm.priorityMovieIds.includes(
                        String(movie.id),
                      );
                      return (
                        <label
                          key={`excluded-${movie.id}`}
                          className={`flex items-center gap-2 text-sm ${prioritized ? "opacity-40" : "cursor-pointer"}`}
                        >
                          <input
                            type="checkbox"
                            checked={excluded}
                            disabled={prioritized}
                            onChange={() =>
                              toggleExcludedMovie(String(movie.id))
                            }
                          />
                          <span className="truncate">{movie.title}</span>
                        </label>
                      );
                    })}
                  </div>
                </div>

                {hasPreview && (
                  <div className="space-y-2">
                    <Label>Kết quả xem trước ({autoPreview.length} suất)</Label>
                    <div className="rounded-md border p-3 bg-muted/30">
                      <div className="text-sm font-medium mb-2">
                        Tổng suất theo phim
                      </div>
                      <div className="grid grid-cols-2 gap-2">
                        {previewMovieStats.map((item) => (
                          <div
                            key={item.movieTitle}
                            className="text-sm rounded border bg-background px-2 py-1 flex items-center justify-between"
                          >
                            <span className="truncate pr-2">
                              {item.movieTitle}
                              {item.priority ? " (ưu tiên)" : ""}
                            </span>
                            <span className="font-semibold">{item.total}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        <Input
                          placeholder="Tìm theo tên phim, phòng, thời gian..."
                          value={previewQuery}
                          onChange={(e) => setPreviewQuery(e.target.value)}
                        />
                        <Select
                          value={previewMode}
                          onValueChange={(value: "list" | "by-day") =>
                            setPreviewMode(value)
                          }
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Chế độ xem" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="list">Danh sách</SelectItem>
                            <SelectItem value="by-day">
                              Xem theo ngày
                            </SelectItem>
                          </SelectContent>
                        </Select>
                      </div>

                      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                        <Select
                          value={previewDateFilter}
                          onValueChange={setPreviewDateFilter}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Lọc ngày" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="all">Tất cả ngày</SelectItem>
                            {previewDateOptions.map((date) => (
                              <SelectItem key={date} value={date}>
                                {new Date(date).toLocaleDateString("vi-VN")}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>

                        <Select
                          value={previewMovieFilter}
                          onValueChange={setPreviewMovieFilter}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Lọc phim" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="all">Tất cả phim</SelectItem>
                            {previewMovieOptions.map((movie) => (
                              <SelectItem key={movie.id} value={movie.id}>
                                {movie.title}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>

                        <Select
                          value={previewHallFilter}
                          onValueChange={setPreviewHallFilter}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Lọc phòng" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="all">Tất cả phòng</SelectItem>
                            {previewHallOptions.map((hall) => (
                              <SelectItem key={hall.id} value={hall.id}>
                                {hall.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>

                        <label className="flex items-center gap-2 text-sm rounded-md border px-3">
                          <input
                            type="checkbox"
                            checked={previewOnlyPriority}
                            onChange={(e) =>
                              setPreviewOnlyPriority(e.target.checked)
                            }
                          />
                          Chỉ phim ưu tiên
                        </label>
                      </div>

                      <div className="grid grid-cols-2 gap-2">
                        <Input
                          type="time"
                          value={previewStartTimeFilter}
                          onChange={(e) =>
                            setPreviewStartTimeFilter(e.target.value)
                          }
                          placeholder="Từ giờ"
                        />
                        <Input
                          type="time"
                          value={previewEndTimeFilter}
                          onChange={(e) =>
                            setPreviewEndTimeFilter(e.target.value)
                          }
                          placeholder="Đến giờ"
                        />
                      </div>

                      <div className="max-h-72 overflow-auto rounded-md border p-2">
                        {previewMode === "by-day" ? (
                          previewGroupedByDay.length > 0 ? (
                            previewGroupedByDay.map((group) => (
                              <div key={group.date} className="mb-3 last:mb-0">
                                <div className="text-sm font-semibold sticky top-0 bg-background py-1">
                                  {new Date(group.date).toLocaleDateString(
                                    "vi-VN",
                                  )}{" "}
                                  ({group.items.length} suất)
                                </div>
                                {group.items.map((item, idx) => (
                                  <div
                                    key={`${group.date}-${item.start_time}-${item.movie_id}-${idx}`}
                                    className="text-sm py-1 border-b last:border-b-0"
                                  >
                                    {new Date(
                                      item.start_time,
                                    ).toLocaleTimeString("vi-VN", {
                                      hour: "2-digit",
                                      minute: "2-digit",
                                    })}
                                    {" - "}
                                    {item.movie_title}
                                    {item.priority ? " (ưu tiên)" : ""}
                                    {" - "}
                                    {item.hall_name}
                                  </div>
                                ))}
                              </div>
                            ))
                          ) : (
                            <div className="text-sm text-muted-foreground py-2">
                              Không có suất nào khớp bộ lọc.
                            </div>
                          )
                        ) : previewItems.length > 0 ? (
                          previewItems.map((item, idx) => (
                            <div
                              key={`${item.start_time}-${item.movie_id}-${idx}`}
                              className="text-sm py-1 border-b last:border-b-0"
                            >
                              {new Date(item.start_time).toLocaleString(
                                "vi-VN",
                              )}{" "}
                              - {item.movie_title}
                              {item.priority ? " (ưu tiên)" : ""}
                              {" - "}
                              {item.hall_name}
                            </div>
                          ))
                        ) : (
                          <div className="text-sm text-muted-foreground py-2">
                            Không có suất nào khớp bộ lọc.
                          </div>
                        )}
                      </div>

                      {previewMode === "list" && (
                        <div className="flex items-center justify-between text-xs text-muted-foreground">
                          <span>
                            Hiển thị{" "}
                            {filteredPreview.length === 0
                              ? 0
                              : (previewPage - 1) * previewPerPage + 1}
                            -
                            {Math.min(
                              previewPage * previewPerPage,
                              filteredPreview.length,
                            )}
                            /{filteredPreview.length}
                          </span>
                          <div className="flex items-center gap-2">
                            <Button
                              variant="outline"
                              size="sm"
                              disabled={previewPage <= 1}
                              onClick={() =>
                                setPreviewPage((p) => Math.max(1, p - 1))
                              }
                            >
                              Trước
                            </Button>
                            <span>
                              {previewPage}/{previewTotalPages}
                            </span>
                            <Button
                              variant="outline"
                              size="sm"
                              disabled={previewPage >= previewTotalPages}
                              onClick={() =>
                                setPreviewPage((p) =>
                                  Math.min(previewTotalPages, p + 1),
                                )
                              }
                            >
                              Sau
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
              <DialogFooter className="sticky bottom-0 bg-background pt-3">
                <Button
                  variant="outline"
                  onClick={() => {
                    setIsAutoDialogOpen(false);
                    setAutoPreview([]);
                    setHasPreview(false);
                    setPreviewQuery("");
                    setPreviewPage(1);
                    setPreviewMode("list");
                    setPreviewDateFilter("all");
                    setPreviewHallFilter("all");
                    setPreviewMovieFilter("all");
                    setPreviewOnlyPriority(false);
                    setPreviewStartTimeFilter("");
                    setPreviewEndTimeFilter("");
                    setRerollToken(0);
                  }}
                >
                  Hủy
                </Button>
                <Button
                  variant="outline"
                  onClick={handleAutoPreview}
                  disabled={autoGenerating}
                >
                  {autoGenerating ? "Đang xử lý..." : "Xem trước"}
                </Button>
                <Button
                  variant="outline"
                  onClick={handleAutoReroll}
                  disabled={autoGenerating || !hasPreview}
                >
                  {autoGenerating ? "Đang xếp lại..." : "Xếp lại"}
                </Button>
                <Button
                  onClick={handleAutoGenerate}
                  disabled={autoGenerating || !hasPreview}
                >
                  {autoGenerating ? "Đang tạo..." : "Tạo lịch từ bản xem trước"}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
            <DialogTrigger asChild>
              <Button className="gap-2">
                <Plus className="w-4 h-4" />
                Thêm Suất Chiếu
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Thêm Suất Chiếu Mới</DialogTitle>
                <DialogDescription>
                  Xếp lịch chiếu phim cho rạp
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div className="space-y-2">
                  <Label htmlFor="movie">Phim</Label>
                  <Select
                    value={formData.movieId}
                    onValueChange={(value) =>
                      setFormData({ ...formData, movieId: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Chọn phim" />
                    </SelectTrigger>
                    <SelectContent>
                      {moviesList.map((movie) => (
                        <SelectItem key={movie.id} value={String(movie.id)}>
                          {movie.title}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="cinema">Rạp</Label>
                  <Select
                    value={formData.cinemaId}
                    onValueChange={(value) =>
                      setFormData({ ...formData, cinemaId: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Chọn rạp" />
                    </SelectTrigger>
                    <SelectContent>
                      {cinemasList.map((cinema) => (
                        <SelectItem key={cinema.id} value={String(cinema.id)}>
                          {cinema.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="hall">Phòng chiếu</Label>
                  <Select
                    value={formData.hallId}
                    onValueChange={(value) =>
                      setFormData({ ...formData, hallId: value })
                    }
                    disabled={!formData.cinemaId || loadingHalls}
                  >
                    <SelectTrigger>
                      <SelectValue
                        placeholder={
                          !formData.cinemaId
                            ? "Chọn rạp trước"
                            : loadingHalls
                              ? "Đang tải..."
                              : hallsList.length === 0
                                ? "Không có phòng"
                                : "Chọn phòng chiếu"
                        }
                      />
                    </SelectTrigger>
                    <SelectContent>
                      {hallsList.map((hall) => (
                        <SelectItem key={hall.id} value={String(hall.id)}>
                          {hall.name} ({hall.total_seats} ghế)
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="date">Ngày chiếu</Label>
                    <Input
                      id="date"
                      type="date"
                      value={formData.date}
                      onChange={(e) =>
                        setFormData({ ...formData, date: e.target.value })
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="time">Giờ chiếu</Label>
                    <Input
                      id="time"
                      type="time"
                      value={formData.time}
                      onChange={(e) =>
                        setFormData({ ...formData, time: e.target.value })
                      }
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="price">Giá vé</Label>
                  <Input
                    id="price"
                    type="number"
                    value={formData.price}
                    onChange={(e) =>
                      setFormData({ ...formData, price: e.target.value })
                    }
                    placeholder="90000"
                  />
                </div>

                {/* Conflict Error Alert */}
                {conflictError && (
                  <Alert className="border-red-500 bg-red-50">
                    <AlertTriangle className="h-4 w-4 text-red-600" />
                    <AlertDescription className="text-red-900">
                      {conflictError}
                    </AlertDescription>
                  </Alert>
                )}

                {/* Quota Warning Alert */}
                {quotaWarning && (
                  <Alert className="border-yellow-500 bg-yellow-50">
                    <AlertTriangle className="h-4 w-4 text-yellow-600" />
                    <AlertDescription className="text-yellow-900">
                      {quotaWarning}
                    </AlertDescription>
                  </Alert>
                )}
              </div>
              <DialogFooter>
                <Button
                  variant="outline"
                  onClick={() => setIsAddDialogOpen(false)}
                >
                  Hủy
                </Button>
                <Button onClick={handleAdd} disabled={!!conflictError}>
                  Thêm
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Tổng suất chiếu</p>
                <p className="text-2xl font-bold">{showtimes.length}</p>
              </div>
              <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
                <CalendarIcon className="w-6 h-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Đã xếp lịch</p>
                <p className="text-2xl font-bold">
                  {showtimes.filter((s) => s.status === "scheduled").length}
                </p>
              </div>
              <div className="w-12 h-12 bg-blue-500/10 rounded-full flex items-center justify-center">
                <Clock className="w-6 h-6 text-blue-500" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">
                  Phim nhiều suất nhất
                </p>
                <p className="text-2xl font-bold">
                  {(() => {
                    const movieCounts: Record<string, number> = {};
                    showtimes.forEach((s) => {
                      movieCounts[s.movieTitle] =
                        (movieCounts[s.movieTitle] || 0) + 1;
                    });
                    const sorted = Object.entries(movieCounts).sort(
                      (a, b) => b[1] - a[1],
                    );
                    return sorted.length > 0 ? sorted[0][1] : 0;
                  })()}
                </p>
                <p className="text-xs text-muted-foreground truncate max-w-[150px]">
                  {(() => {
                    const movieCounts: Record<string, number> = {};
                    showtimes.forEach((s) => {
                      movieCounts[s.movieTitle] =
                        (movieCounts[s.movieTitle] || 0) + 1;
                    });
                    const sorted = Object.entries(movieCounts).sort(
                      (a, b) => b[1] - a[1],
                    );
                    return sorted.length > 0 ? sorted[0][0] : "-";
                  })()}
                </p>
              </div>
              <div className="w-12 h-12 bg-green-500/10 rounded-full flex items-center justify-center">
                <Film className="w-6 h-6 text-green-500" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Tổng vé đã bán</p>
                <p className="text-2xl font-bold">
                  {showtimes
                    .reduce(
                      (sum, s) => sum + (s.totalSeats - s.availableSeats),
                      0,
                    )
                    .toLocaleString("vi-VN")}
                </p>
              </div>
              <div className="w-12 h-12 bg-purple-500/10 rounded-full flex items-center justify-center">
                <Armchair className="w-6 h-6 text-purple-500" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search & Table */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between gap-4">
            <CardTitle>Danh Sách Lịch Chiếu</CardTitle>
            <div className="flex items-center gap-2 flex-wrap">
              <Select
                value={searchCategory}
                onValueChange={(value: "movie" | "cinema" | "room") =>
                  setSearchCategory(value)
                }
              >
                <SelectTrigger className="w-40">
                  <SelectValue placeholder="Tìm theo..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="movie">Tên phim</SelectItem>
                  <SelectItem value="cinema">Tên rạp</SelectItem>
                  <SelectItem value="room">Tên phòng</SelectItem>
                </SelectContent>
              </Select>
              <div className="relative w-48">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Tìm kiếm..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
              <div className="flex items-center gap-1 text-sm text-muted-foreground">
                <span>Từ</span>
                <Input
                  type="date"
                  value={dateFrom}
                  onChange={(e) => setDateFrom(e.target.value)}
                  className="w-36 h-9"
                />
                <span>đến</span>
                <Input
                  type="date"
                  value={dateTo}
                  onChange={(e) => setDateTo(e.target.value)}
                  className="w-36 h-9"
                />
                {(dateFrom || dateTo) && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      setDateFrom("");
                      setDateTo("");
                    }}
                    className="h-9 px-2 text-xs"
                  >
                    Xóa lọc
                  </Button>
                )}
              </div>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Phim</TableHead>
                <TableHead>Rạp</TableHead>
                <TableHead>Phòng</TableHead>
                <TableHead>Ngày/Giờ</TableHead>
                <TableHead>Giá Vé</TableHead>
                <TableHead>Ghế Trống</TableHead>
                <TableHead>Trạng Thái</TableHead>
                <TableHead className="text-right">Thao Tác</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {paginatedShowtimes.map((showtime) => (
                <TableRow key={showtime.id}>
                  <TableCell className="font-medium">
                    {showtime.movieTitle}
                  </TableCell>
                  <TableCell>{showtime.cinemaName}</TableCell>
                  <TableCell>{showtime.room}</TableCell>
                  <TableCell>
                    <div className="text-sm">
                      <div>{formatDate(showtime.date)}</div>
                      <div className="text-muted-foreground font-medium">
                        {showtime.time} -{" "}
                        {new Date(
                          new Date(
                            showtime.date + "T" + showtime.time,
                          ).getTime() +
                            showtime.duration * 60000,
                        ).toLocaleTimeString("vi-VN", {
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell className="font-medium">
                    {Number(showtime.price).toLocaleString("vi-VN")}đ
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">
                      {showtime.availableSeats}/{showtime.totalSeats}
                      <div className="text-xs text-muted-foreground">
                        {Math.round(
                          (showtime.availableSeats / showtime.totalSeats) * 100,
                        )}
                        %
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>{getStatusBadge(showtime.status)}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex items-center justify-end gap-2">
                      <Button
                        variant="ghost"
                        size="icon"
                        title="Xem sơ đồ ghế"
                        onClick={() =>
                          navigate(
                            `/admin/seats?hallId=${showtime.hallId}&cinemaId=${showtime.cinemaId}`,
                          )
                        }
                      >
                        <Armchair className="w-4 h-4 text-blue-500" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleEdit(showtime)}
                      >
                        <Edit className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() =>
                          handleDelete(showtime.id, showtime.movieTitle)
                        }
                      >
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {totalPages > 1 && (
            <div className="mt-4 flex justify-center">
              <Pagination>
                <PaginationContent>
                  <PaginationItem>
                    <PaginationPrevious
                      href="#"
                      onClick={(e) => {
                        e.preventDefault();
                        if (currentPage > 1) setCurrentPage(currentPage - 1);
                      }}
                      className={
                        currentPage === 1
                          ? "pointer-events-none opacity-50"
                          : ""
                      }
                    />
                  </PaginationItem>
                  {[...Array(totalPages)].map((_, i) => (
                    <PaginationItem key={i + 1}>
                      <PaginationLink
                        href="#"
                        isActive={currentPage === i + 1}
                        onClick={(e) => {
                          e.preventDefault();
                          setCurrentPage(i + 1);
                        }}
                      >
                        {i + 1}
                      </PaginationLink>
                    </PaginationItem>
                  ))}
                  <PaginationItem>
                    <PaginationNext
                      href="#"
                      onClick={(e) => {
                        e.preventDefault();
                        if (currentPage < totalPages)
                          setCurrentPage(currentPage + 1);
                      }}
                      className={
                        currentPage === totalPages
                          ? "pointer-events-none opacity-50"
                          : ""
                      }
                    />
                  </PaginationItem>
                </PaginationContent>
              </Pagination>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Edit Showtime Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Chỉnh Sửa Suất Chiếu</DialogTitle>
          </DialogHeader>
          {selectedShowtime && (
            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-movie">Phim</Label>
                  <Select
                    value={selectedShowtime.movieId}
                    onValueChange={(value) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        movieId: value,
                        movieTitle:
                          moviesList.find((m) => String(m.id) === value)
                            ?.title || "",
                      })
                    }
                  >
                    <SelectTrigger id="edit-movie">
                      <SelectValue placeholder="Chọn phim" />
                    </SelectTrigger>
                    <SelectContent>
                      {moviesList.map((movie) => (
                        <SelectItem key={movie.id} value={String(movie.id)}>
                          {movie.title}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-cinema">Rạp</Label>
                  <Select
                    value={selectedShowtime.cinemaId}
                    onValueChange={(value) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        cinemaId: value,
                        cinemaName:
                          cinemasList.find((c) => String(c.id) === value)
                            ?.name || "",
                      })
                    }
                  >
                    <SelectTrigger id="edit-cinema">
                      <SelectValue placeholder="Chọn rạp" />
                    </SelectTrigger>
                    <SelectContent>
                      {cinemasList.map((cinema) => (
                        <SelectItem key={cinema.id} value={String(cinema.id)}>
                          {cinema.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-room">Phòng</Label>
                  <Input
                    id="edit-room"
                    value={selectedShowtime.room}
                    onChange={(e) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        room: e.target.value,
                      })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-date">Ngày Chiếu</Label>
                  <Input
                    id="edit-date"
                    type="date"
                    value={selectedShowtime.date}
                    onChange={(e) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        date: e.target.value,
                      })
                    }
                  />
                </div>
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-time">Giờ Chiếu</Label>
                  <Input
                    id="edit-time"
                    type="time"
                    value={selectedShowtime.time}
                    onChange={(e) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        time: e.target.value,
                      })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-price">Giá Vé (VNĐ)</Label>
                  <Input
                    id="edit-price"
                    type="number"
                    value={selectedShowtime.price}
                    onChange={(e) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        price: Number(e.target.value),
                      })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-total-seats">Tổng Ghế</Label>
                  <Input
                    id="edit-total-seats"
                    type="number"
                    value={selectedShowtime.totalSeats}
                    onChange={(e) =>
                      setSelectedShowtime({
                        ...selectedShowtime,
                        totalSeats: Number(e.target.value),
                      })
                    }
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-status">Trạng Thái</Label>
                <Select
                  value={selectedShowtime.status}
                  onValueChange={(
                    value: "scheduled" | "ongoing" | "completed" | "cancelled",
                  ) =>
                    setSelectedShowtime({
                      ...selectedShowtime,
                      status: value,
                    })
                  }
                >
                  <SelectTrigger id="edit-status">
                    <SelectValue placeholder="Chọn trạng thái" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="scheduled">Đã Lên Lịch</SelectItem>
                    <SelectItem value="ongoing">Đang Chiếu</SelectItem>
                    <SelectItem value="completed">Hoàn Thành</SelectItem>
                    <SelectItem value="cancelled">Đã Hủy</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
            >
              Hủy
            </Button>
            <Button onClick={handleUpdate}>Cập Nhật</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AdminScheduler;
